jobs:
  sync:
    if: github.repository_owner == 'mollyim'
    name: Sync
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: upstream
        token: ${{ secrets.PUBLISH_PAT || secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Fetch and merge upstream
      run: 'git remote add upstream https://github.com/signalapp/Signal-Android.git

        git fetch upstream

        git merge --ff-only upstream/main

        '
    - continue-on-error: true
      name: Push changes
      run: 'git push origin upstream

        git tag | grep -xP ''v\d+(?:\.\d+){2,3}'' | xargs -r git push origin

        '
name: Sync upstream
on:
  repository_dispatch:
    types: trigger-ga___sync.yml
