jobs:
  test:
    env:
      GRADLE_OPTS: -Dorg.gradle.project.kotlin.compiler.execution.strategy=in-process
    name: Run tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Run tests
      run: ./gradlew build --no-daemon
    - continue-on-error: true
      if: failure()
      name: Archive reports for failed tests
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: '*/build/reports'
  wrapper_validation:
    name: Validate Gradle wrapper
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Run wrapper validation
      uses: gradle/wrapper-validation-action@v1
name: Test
on:
  repository_dispatch:
    types: trigger-ga___test.yml
permissions:
  contents: read
